apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: staging
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5205
  selector:
    app: backend
