apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "16Gi"  
    requests.cpu: "2"
    requests.memory: "6Gi" 
