apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: staging
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: webstore-frontend:staging-new
        imagePullPolicy: IfNotPresent  # Critical fix
        ports:
        - containerPort: 80
        env:
          - name: BACKEND_URL
            value: "http://localhost:5300"  
        resources:
          requests:
            cpu: "20m"
            memory: "48Mi"
          limits:
            cpu: "50m"
            memory: "96Mi"
      nodeSelector:
        kubernetes.io/hostname: minikube