apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5205
      nodePort: 30500  # NodePort within valid range (30000–32767)
  selector:
    app: backend
