apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: production  
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: database
