apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database
  namespace: production  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # increase storage size for production if needed
