apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production  # Changed namespace to production
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
