apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota  
  namespace: production  
spec:
  hard:
    limits.cpu: "8"  
    limits.memory: "24Gi"  
    requests.cpu: "4"  
    requests.memory: "12Gi"  
