apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database
  namespace: production  
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data  
